/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registroperiodicoonline2;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Your Name <Juan A. García Muelas (juangmuelas@hotmail.com)>
 */
public class Usuarios extends javax.swing.JFrame {
    
     ArrayList<Usuario> usuariosList= new ArrayList<Usuario>();

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        
        buttonGroupPremium.add(premium);
        buttonGroupPremium.add(noPremium);
        
       
        
        //Centramos la ventana con esta orden.
       this.setLocationRelativeTo(null);
        
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPremium = new javax.swing.ButtonGroup();
        etiquetaUsuario = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        botonAnadir = new javax.swing.JButton();
        etiquetaContraseña = new javax.swing.JLabel();
        textoContrasena = new javax.swing.JTextField();
        botonLimpiar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonIngresos = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        etiquetaDescuento = new javax.swing.JLabel();
        textoDescuento = new javax.swing.JTextField();
        jPanelPremium = new javax.swing.JPanel();
        premium = new javax.swing.JRadioButton();
        noPremium = new javax.swing.JRadioButton();
        botonCuentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios");

        etiquetaUsuario.setText("Usuario:");

        botonAnadir.setText("Añadir");
        botonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirActionPerformed(evt);
            }
        });

        etiquetaContraseña.setText("Contraseña:");

        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonIngresos.setText("Ingresos");
        botonIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresosActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        etiquetaDescuento.setText("Descuento:");

        jPanelPremium.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente Premium"));

        buttonGroupPremium.add(premium);
        premium.setText("Si");

        buttonGroupPremium.add(noPremium);
        noPremium.setText("No");

        javax.swing.GroupLayout jPanelPremiumLayout = new javax.swing.GroupLayout(jPanelPremium);
        jPanelPremium.setLayout(jPanelPremiumLayout);
        jPanelPremiumLayout.setHorizontalGroup(
            jPanelPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPremiumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(premium)
                    .addComponent(noPremium))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanelPremiumLayout.setVerticalGroup(
            jPanelPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPremiumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(premium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noPremium)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonCuentas.setText("cuentas");
        botonCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaContraseña)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaDescuento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonIngresos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonCuentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaUsuario)
                    .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAnadir))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(botonIngresos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCuentas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirActionPerformed
        // Creamos un objeto Usuario. 
        
        Usuario user= new Usuario();
        boolean correcto =true;
        
        //Ahora, comprobamos la contraseña y de no ser correcta, el error.
        Pattern mail = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        
        Matcher mCorreo = mail.matcher(textoUsuario.getText());
        
        if(mCorreo.matches()){
            user.setEmail(textoUsuario.getText());
        }else{
            JOptionPane.showMessageDialog(this,"Formato incorrecto", "Error",JOptionPane.ERROR_MESSAGE);
            correcto= false;
        }
       
        user.setContrasena(textoContrasena.getText());
        
        try {
            user.setImporte(Double.parseDouble(textoDescuento.getText()));
        } catch (NumberFormatException e) { 
            JOptionPane.showMessageDialog(this,"Error en el importe", "error", JOptionPane.ERROR_MESSAGE);
            correcto = false;
        }
        
        if (premium.isSelected()) {
            user.setPremium(true);
            
        } else {
            user.setPremium(false);
        }
        
        if(correcto){
            usuariosList.add(user);
            JOptionPane.showMessageDialog(this,"Usuario añadido", "Añadido", JOptionPane.INFORMATION_MESSAGE);
            
        }else {
            JOptionPane.showMessageDialog(this,"No se añadió al usuario", "error", JOptionPane.ERROR_MESSAGE);
        }
        verLista();
    }//GEN-LAST:event_botonAnadirActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        
        textoUsuario.setText("");
        textoContrasena.setText("");
        textoDescuento.setText("");
        buttonGroupPremium.clearSelection();
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // La búsqueda es por el identificador (mail)
        Usuario user = new Usuario();
        boolean encontrado = false;
        
        String email;
        email = textoUsuario.getText();
        
        if (!usuariosList.isEmpty()) {
            for(int i = 0; i<usuariosList.size()&&!encontrado;i++){  
                user = usuariosList.get(i);
                if(email.equalsIgnoreCase(user.getEmail())){
                    encontrado = true;
                }
            }
            
            if(encontrado){
                textoUsuario.setText(user.getEmail());
                textoContrasena.setText(user.getContrasena());
                textoDescuento.setText(user.getImporte()+"");
                if(user.isPremium()){
                    premium.setSelected(true);
                    JOptionPane.showMessageDialog(this,"El usuario que busca es " + email , ".",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    noPremium.setSelected(true);
                    JOptionPane.showMessageDialog(this,"El usuario que busca es " + email , ".",JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this,"No existen coincidencias", "No encontrado", JOptionPane.ERROR_MESSAGE);
            }   
        } else {
            JOptionPane.showMessageDialog(this,"No hay usuarios", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresosActionPerformed
        
        double total=0;
             
       for(int i = 0 ; i < this.usuariosList.size() ; i++){
           if(usuariosList.get(i).isPremium()){
               total += 35.5;
           }else{
               total += 20.5;
           }
           
           total -= usuariosList.get(i).getImporte();
       }
        JOptionPane.showMessageDialog(this,"El total de ingresos es " + total + " euros.", "Ingresos",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonIngresosActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuentasActionPerformed
        
        int premium=0;
        for(int i = 0; i < usuariosList.size() ; i++){
            if(usuariosList.get(i).isPremium()){
                premium ++;
            }
        }
        JOptionPane.showMessageDialog(this,"El total de premium es " + premium + " usuarios.", "Premium",JOptionPane.INFORMATION_MESSAGE);
        
        int normal = usuariosList.size()-premium;
        JOptionPane.showMessageDialog(this,"El total de normales es " + normal + " usuarios.", "Normal",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonCuentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }
    
    public void verLista(){
        System.out.println("Listado de datos");
        
        for( int i= 0; i < usuariosList.size(); i++){
            
            System.out.println(">"+usuariosList.get(i)) ;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnadir;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCuentas;
    private javax.swing.JButton botonIngresos;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonSalir;
    private javax.swing.ButtonGroup buttonGroupPremium;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaDescuento;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JPanel jPanelPremium;
    private javax.swing.JRadioButton noPremium;
    private javax.swing.JRadioButton premium;
    private javax.swing.JTextField textoContrasena;
    private javax.swing.JTextField textoDescuento;
    private javax.swing.JTextField textoUsuario;
    // End of variables declaration//GEN-END:variables
}
